import { DashboardData } from "./types";

export const defaultData: DashboardData = {
  income: {
    baseSalary: 7500,      // User 1 monthly base
    ote: 2500,             // User 1 monthly OTE/bonus — firewalled
    user2BaseSalary: 5200, // User 2 monthly base
    user2Ote: 800,         // User 2 monthly OTE/bonus — firewalled
  },
  subscriptions: [
    {
      id: "sub_netflix",
      name: "Netflix",
      amount: 22.99,
      frequency: "Monthly",
      category: "Shared",
      icon: "netflix",
      dueDay: 8,
      color: "#E50914",
    },
    {
      id: "sub_spotify",
      name: "Spotify",
      amount: 10.99,
      frequency: "Monthly",
      category: "Individual_1",
      icon: "spotify",
      dueDay: 14,
      color: "#1DB954",
    },
    {
      id: "sub_apple",
      name: "Apple TV+",
      amount: 9.99,
      frequency: "Monthly",
      category: "Shared",
      icon: "apple",
      dueDay: 20,
      color: "#555555",
    },
    {
      id: "sub_hulu",
      name: "Hulu",
      amount: 17.99,
      frequency: "Monthly",
      category: "Shared",
      icon: "hulu",
      dueDay: 3,
      color: "#1CE783",
    },
    {
      id: "sub_youtube",
      name: "YouTube Premium",
      amount: 13.99,
      frequency: "Monthly",
      category: "Individual_2",
      icon: "youtube",
      dueDay: 18,
      color: "#FF0000",
    },
    {
      id: "sub_amazon",
      name: "Amazon Prime",
      amount: 14.99,
      frequency: "Monthly",
      category: "Shared",
      icon: "amazon",
      dueDay: 22,
      color: "#FF9900",
    },
    {
      id: "sub_gym",
      name: "Gym Membership",
      amount: 49.99,
      frequency: "Monthly",
      category: "Individual_1",
      icon: "gym",
      dueDay: 1,
      color: "#3B82F6",
    },
    {
      id: "sub_icloud",
      name: "iCloud Storage",
      amount: 2.99,
      frequency: "Monthly",
      category: "Individual_1",
      icon: "icloud",
      dueDay: 5,
      color: "#3B82F6",
    },
  ],
  fixedExpenses: [
    {
      id: "exp_rent",
      name: "Rent",
      amount: 2400,
      splitType: "Shared",
      icon: "home",
      category: "Housing",
    },
    {
      id: "exp_electricity",
      name: "Electricity",
      amount: 130,
      splitType: "Shared",
      icon: "zap",
      category: "Utilities",
    },
    {
      id: "exp_internet",
      name: "Internet",
      amount: 85,
      splitType: "Shared",
      icon: "wifi",
      category: "Utilities",
    },
    {
      id: "exp_groceries",
      name: "Groceries",
      amount: 600,
      splitType: "Shared",
      icon: "shopping-cart",
      category: "Food",
    },
    {
      id: "exp_car_ins",
      name: "Car Insurance",
      amount: 180,
      splitType: "Individual_1",
      icon: "car",
      category: "Transport",
    },
    {
      id: "exp_phone1",
      name: "Phone Plan (User 1)",
      amount: 65,
      splitType: "Individual_1",
      icon: "phone",
      category: "Utilities",
    },
    {
      id: "exp_phone2",
      name: "Phone Plan (User 2)",
      amount: 55,
      splitType: "Individual_2",
      icon: "phone",
      category: "Utilities",
    },
    {
      id: "exp_dining",
      name: "Dining Out",
      amount: 350,
      splitType: "Shared",
      icon: "utensils",
      category: "Food",
    },
  ],
  budgets: [
    { id: "bud_housing", category: "Housing", cap: 2500 },
    { id: "bud_utilities", category: "Utilities", cap: 300 },
    { id: "bud_food", category: "Food", cap: 900 },   // intentionally below 950 spend to demo over-budget
    { id: "bud_transport", category: "Transport", cap: 250 },
  ],
  splitRatioUser1: 0.6,
  user1Name: "User 1",
  user2Name: "User 2",
};
